### PR TITLE
basic-code-cleanup1 for hubstats

### PR DESCRIPTION
**Pull request by emmasax1**
Description and Impact
----------------------
There shouldn't be too much impact to the actual product. I tested it locally, and nothing broke. I deleted a file (app/views/repos/index.html.erb) that was never used from last summer.

Deploy Plan
-----------
There are migrations present in this application, but I don't think they're involved in anything I did...

Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.

URLs
----
> Links to bug tickets or user stories.

QA Plan
-------
- [ ] check that README.rdoc was replaced with README.md (by replaced, I just mean deleted and that README.md is a new file)
- [ ] If you want to test is manually, play around with the test/dummy (I did and nothing is breaking)

#### Happy Path Scenarios
- [ ] Example Happy Path scenario

#### Additional Scenarios (Edge Case, Negative, etc.)
- [ ] Example Edge Case scenario

#### Regression Scenarios
- [ ] Example Regression item on related feature

### CODE REVIEW

**Comment by emmasax1** [comment]
:octocat: Merged into staging.2015.05.21.

**Comment by emmasax1** [comment]
:octocat: Merged into staging.2015.05.21.

**Comment by emmasax1** [comment]
:octocat: Merged into staging.2015.05.21.

**Comment by elliothursh** [comment]
CR++

**Pull request merged**
