### PR TITLE
Cleaning up code; fixing bug with repo filter; adding pretty footer

### PR DESCRIPTION
**Pull request by emmasax1**
Description and Impact
----------------------
NOTE: This PR will overwrite [PR 67](https://github.com/sportngin/hubstats/pull/67), so I will close that PR.
This PR fixes a bug with the repo filter on the users page, adds a nice looking footer with a link to the github code (which is super easy to take out), and cleans up unnecessary code and comments.

Deploy Plan
-----------
No new migrations with this PR.

Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.

URLs
----
> Links to bug tickets or user stories.

QA Plan
-------
Run Hubstats locally. Feel free to look at the pretty footer, and note the datepicker still exists.

### CODE REVIEW

**Comment by lukeludwig** [comment]
Great work commenting the code. Nice improvement.

**Comment by NickLaMuro** [comment]
These changes seem fine.

**Comment by emmasax1** [comment]
@NickLaMuro so :shipit:

**Comment by NickLaMuro** [comment]
Yup.

**Pull request merged**
